// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCurrencyConversions.Infrastructure;

namespace SimpleCurrencyConversions.Infrastructure.Migrations
{
    [DbContext(typeof(SQLiteDBContext))]
    [Migration("20201109002425_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("SimpleCurrencyConversions.Domain.CurrencyConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConvertedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputCurrency")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InputValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conversions");
                });
#pragma warning restore 612, 618
        }
    }
}
